Initialization via Job Packet and Rename DataQueueHandler to DataProvider
QuantConnect/Lean.DataSource.CoinAPI pull request #2
Opened 2024-02-21 18:37 UTC by Romazes

#### Description

1. Feature Enhancement: Initialization via Job Packet
  - Implements initialization functionality through **Job packets**, enhancing the efficiency and flexibility of the system.
Provides a streamlined method for initializing processes, improving overall performance and maintainability.

2. Code Refactoring: Renaming DataQueueHandler to DataProvider
  - Renames the **DataQueueHandler** class to **DataProvider** for improved clarity and consistency in naming conventions.
Enhances code readability and understandability, aligning with best practices for naming conventions.

3. Use Globals for credentials access for subscription validation.
  - This follows https://github.com/QuantConnect/Lean/pull/7796

#### Related Issue

N/A

#### Motivation and Context

1. Feature Enhancement: Initialization via Job Packet
  - As the system evolves, there is a growing need for a more robust and flexible initialization process. Implementing initialization through Job packets provides an efficient and adaptable solution, enhancing overall system efficiency and maintainability.
2. Code Refactoring: Renaming DataQueueHandler to DataProvider
  - Clear and consistent naming conventions are crucial for improving code maintainability. Renaming DataQueueHandler to DataProvider aligns with best practices, improving code clarity and making it easier for developers to understand and work with the codebase.

#### Requires Documentation Change

N/A

#### How Has This Been Tested?

To ensure the robustness and correctness of the Job initialization process, the PR have been implemented specific test cases.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** [document](https://github.com/QuantConnect/Lean/blob/master/CONTRIBUTING.md).
- [x] I have added tests to cover my changes. 
- [x] All new and existing tests passed.
- [x] My branch follows the naming convention `bug-<issue#>-<description>` or `feature-<issue#>-<description>`

2024-02-22 21:13 UTC, jhonabreul requested changes
Nice work! Leaving a few comments

2024-02-22 21:13 UTC, jhonabreul commented on QuantConnect.CoinAPI/CoinAPIDataDownloader.cs
> +                return null;
I think the downloader could still return empty is the history provider returns null. It's a different use case

2024-02-22 21:13 UTC, jhonabreul commented on QuantConnect.CoinAPI/CoinApiDataHistoryProvider.cs
> +                return null;
You could keep some flags to log this errors only once and not flood the output. See https://github.com/QuantConnect/Lean.Brokerages.Bitfinex/blob/14f8ba19a3b8fa1fe73da5724b102c877320f488/QuantConnect.BitfinexBrokerage/BitfinexBrokerage.cs#L368-L373

2024-02-22 21:13 UTC, jhonabreul commented on QuantConnect.CoinAPI/CoinApiDataProvider.cs
> +            // ValidateSubscription();
Whops

2024-02-22 21:13 UTC, jhonabreul commented on QuantConnect.CoinAPI/CoinApiDataProvider.cs
> +            else
The `else` might not be necessary here

2024-02-22 21:44 UTC, jhonabreul commented on QuantConnect.CoinAPI/CoinAPIDataDownloader.cs
> +                return null;
Don't mind this one 👌

2024-02-23 11:08 UTC, Romazes commented on QuantConnect.CoinAPI/CoinAPIDataDownloader.cs
> +                return null;
https://github.com/QuantConnect/Lean/pull/7812

2024-02-23 15:04 UTC, jhonabreul approved these changes

2024-02-27 13:23 UTC, Martin-Molinero approved these changes

2024-02-27 13:23 UTC, merged